services:
  db:
    build: ./db
    container_name: db
    environment:
      POSTGRES_USER: aura_root
      POSTGRES_PASSWORD: aura_password
      POSTGRES_DB: aura_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "aura_root", "-d", "aura_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth_db:
    build: ./auth-db
    container_name: auth_db
    environment:
      POSTGRES_USER: aura_root
      POSTGRES_PASSWORD: aura_password
      POSTGRES_DB: auth_db
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "aura_root", "-d", "auth_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  storage:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: storage
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: aura_root
      MINIO_ROOT_PASSWORD: aura_password
    volumes:
      - storage_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  memory_db:
    image: redis:8.2
    container_name: memory_db
    ports:
      - "6379:6379"
    volumes:
      - memory_db_data:/data
    command: [ "redis-server", "--save", "--appendonly", "no" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 5

  queue:
    image: rabbitmq:4.1-management
    container_name: queue
    environment:
      RABBITMQ_DEFAULT_USER: aura_root
      RABBITMQ_DEFAULT_PASS: aura_password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - queue_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  llm:
    build: ./llm
    container_name: llm
    ports:
      - "11434:11434"
    volumes:
      - llm_data:/root/.ollama

volumes:
  db_data:
  auth_db_data:
  storage_data:
  memory_db_data:
  queue_data:
  llm_data: